*&---------------------------------------------------------------------*
*& Report Z_ACTIVE_CR
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z_ACTIVE_CR1.

*DATA: lo_class TYPE REF TO CL_USMD_WF_BO_SERVICE.
*DATA: lv_ED_APPLOG_ACTION TYPE STRING,
*lv_ED_APPLOG_EXTNUM TYPE BALNREXT,
*lv_ED_APPLOG_OBJ TYPE BALOBJ_D,
*lv_ED_APPLOG_SUBOBJ TYPE BALSUBOBJ,
*lv_ED_RESULT TYPE SYSUBRC,
*lv_EF_ACTIVATION_ERROR TYPE USMD_FLG,
*lv_EF_SNAPSHOT_DIFF TYPE USMD_FLG,
*lv_ET_MESSAGE TYPE USMD_T_MESSAGE,
*lv_ID_CREQUEST TYPE USMD_CREQUEST,
*lv_ID_RELEASED_BY TYPE SYUNAME,
*lv_IF_IGNORE_SNAPSHOT_DIFF TYPE USMD_FLG,
*lv_IF_NO_DISTRIBUTE TYPE USMD_FLG,
*lv_IF_WRITE_APPLOG TYPE USMD_FLG,
*lv_other TYPE c.
*
*CL_USMD_WF_BO_SERVICE->ACTIVATE_CREQUEST(
*EXPORTING
*ID_CREQUEST = '4193'
*ID_RELEASED_BY = 'i511972'
**IF_IGNORE_SNAPSHOT_DIFF = lv_IF_IGNORE_SNAPSHOT_DIFF
**IF_NO_DISTRIBUTE = lv_IF_NO_DISTRIBUTE
**IF_WRITE_APPLOG = lv_IF_WRITE_APPLOG
*IMPORTING
*ED_APPLOG_ACTION = lv_ED_APPLOG_ACTION
*ED_APPLOG_EXTNUM = lv_ED_APPLOG_EXTNUM
*ED_APPLOG_OBJ = lv_ED_APPLOG_OBJ
*ED_APPLOG_SUBOBJ = lv_ED_APPLOG_SUBOBJ
*ED_RESULT = lv_ED_RESULT
*EF_ACTIVATION_ERROR = lv_EF_ACTIVATION_ERROR
*EF_SNAPSHOT_DIFF = lv_EF_SNAPSHOT_DIFF
*ET_MESSAGE = lv_ET_MESSAGE ).
*BREAK-POINT.

*DATA: lo_class TYPE REF TO IF_USMD_CREQUEST_API.
DATA: lv_ET_ENTITY_DATA_ACTIVATED TYPE USMD_TS_ENTITY_DATA_ALL,
lv_ET_MESSAGE TYPE USMD_T_MESSAGE,
lv_other TYPE c.

   DATA :
      lr_crequest                 TYPE REF TO if_usmd_crequest_api.

   CALL METHOD cl_usmd_crequest_api=>get_instance
      EXPORTING
        iv_crequest          = '4934'
      IMPORTING
        re_inst_crequest_api = lr_crequest.
lr_crequest->enqueue_crequest(

  ).
lr_crequest->ACTIVATE_CREQUEST(
IMPORTING
ET_ENTITY_DATA_ACTIVATED = lv_ET_ENTITY_DATA_ACTIVATED
ET_MESSAGE = lv_ET_MESSAGE ).
BREAK-POINT.
